[phases.setup]
nixPkgs = ["...", "chromium", "chromium-driver", "nodejs"]
aptPkgs = ["fonts-liberation", "libasound2", "libatk-bridge2.0-0", "libatk1.0-0", "libatspi2.0-0", "libcups2", "libdbus-1-3", "libdrm2", "libgbm1", "libgtk-3-0", "libnspr4", "libnss3", "libxcomposite1", "libxdamage1", "libxfixes3", "libxkbcommon0", "libxrandr2", "xdg-utils"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "npm start"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROME_BIN = "/nix/var/nix/profiles/default/bin/chromium"
NODE_ENV = "production"