[build]
  builder = "nixpacks"

[deploy]
  startCommand = "node server-production.js"
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 3

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"